image: crystallang/crystal

stages:
- test
- deploy

cache:
  paths:
  - doc/

spec:
  stage: test
  script:
  - crystal spec
  - crystal doc

pages:
  stage: deploy
  script:
  - mv doc public
  artifacts:
    paths: [public]
  only: [master]
